name: rust ci 

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]
                rust: [ stable]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.rust }}
                  override: true

            - name: Run tests
              run: cargo test --all-features --verbose

            - name: Run Build
              run: cargo build --release --all-features --verbose
            
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: rust-binary-artifacts
                path: target/release/